<script src="{{STATIC_URL}}js/jquery-1.7.1.js"></script>
<script src="{{STATIC_URL}}bootstrap-2.2.2/js/bootstrap-tab.js"></script>
<script src="{{STATIC_URL}}bootstrap-2.2.2/js/bootstrap-scrollspy.js"></script>
<script src="{{STATIC_URL}}bootstrap-2.2.2/js/bootstrap-dropdown.js"></script>
<script src="{{STATIC_URL}}bootstrap-2.2.2/js/bootstrap-collapse.js"></script>
<script src="{{STATIC_URL}}bootstrap-2.2.2/js/bootstrap-alert.js"></script>
<script src="{{STATIC_URL}}backbone/underscore-1.4.3-min.js"></script>
<script src="{{STATIC_URL}}backbone/laconic.js"></script>
<script src="{{STATIC_URL}}backbone/json/json2.js"></script>
<script src="{{STATIC_URL}}backbone/backbone-0.9.9-min.js"></script>
<script src="{% url backbone.api_views.backbone_js %}"></script>
<script src="{{STATIC_URL}}backbone/search.js"></script>
